// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8DSmc5MlW-zmk1eI2wneyEyG2CqCI9c',
    appId: '1:780972263409:web:89bcbc02fdd31df36f6650',
    messagingSenderId: '780972263409',
    projectId: 'myapp-dcfce',
    authDomain: 'myapp-dcfce.firebaseapp.com',
    storageBucket: 'myapp-dcfce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAC2-uieA0W-m7lfvf8LLMCNOBBCef4U',
    appId: '1:780972263409:android:4bad1a61da3c8bc86f6650',
    messagingSenderId: '780972263409',
    projectId: 'myapp-dcfce',
    storageBucket: 'myapp-dcfce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXkRqiDFg9TKBeSSK1VSWa0O9XtslLQ9k',
    appId: '1:780972263409:ios:6b3c91031cd720656f6650',
    messagingSenderId: '780972263409',
    projectId: 'myapp-dcfce',
    storageBucket: 'myapp-dcfce.appspot.com',
    iosClientId: '780972263409-56bo00cp0ussnvmql6urb3hjg441li17.apps.googleusercontent.com',
    iosBundleId: 'com.example.meauApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXkRqiDFg9TKBeSSK1VSWa0O9XtslLQ9k',
    appId: '1:780972263409:ios:6b3c91031cd720656f6650',
    messagingSenderId: '780972263409',
    projectId: 'myapp-dcfce',
    storageBucket: 'myapp-dcfce.appspot.com',
    iosClientId: '780972263409-56bo00cp0ussnvmql6urb3hjg441li17.apps.googleusercontent.com',
    iosBundleId: 'com.example.meauApp',
  );
}
