// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoB0Xrz42jk0R4BWS9PPRxHiYqqglLho',
    appId: '1:804956369287:web:5f6b97a6974fc5baf36322',
    messagingSenderId: '804956369287',
    projectId: 'meau-app-e5a55',
    authDomain: 'meau-app-e5a55.firebaseapp.com',
    storageBucket: 'meau-app-e5a55.appspot.com',
    measurementId: 'G-PPV4EEC2HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxh9PB4GyHl1tGOpkoJs5Au25_K6KxH3w',
    appId: '1:804956369287:android:ae5bcb3477308795f36322',
    messagingSenderId: '804956369287',
    projectId: 'meau-app-e5a55',
    storageBucket: 'meau-app-e5a55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AhHjfXyDNAGOu8MmMhCPJbxYUz85tsk',
    appId: '1:804956369287:ios:8f997966d8b3d3e7f36322',
    messagingSenderId: '804956369287',
    projectId: 'meau-app-e5a55',
    storageBucket: 'meau-app-e5a55.appspot.com',
    iosClientId: '804956369287-uukbd9aal08p9ffekckn2aigu88c0ag1.apps.googleusercontent.com',
    iosBundleId: 'com.example.meauApp',
  );
}
